apiVersion: v1
kind: Pod
metadata:
  name: telegram-bot
spec:
  containers:
    - name: telegram-bot
      image: nicopaez/telegrambot:0.0.7
      env:
        - name: TELEGRAM_TOKEN
          value: redacted
