version: '3'

services:
    web:
        image: nicopaez/password-api
        deploy:
          replicas: 2

    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - web